// Generated by web_artifact_build from server/src/privileged.ts. Do not edit.
import { definePrivilegedContracts, z } from "@hatch/space-sdk";

export const privileged = definePrivilegedContracts({
  runIsolationForest: {
    request: z.object({
      outlets: z.array(z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.null()]))),
      bills: z.array(z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.null()]))),
      returns: z.array(z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.null()]))),
      wastage: z.array(z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.null()]))),
      costs: z.array(z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.null()]))),
    }),
    response: z.object({
      status: z.enum(["completed", "insufficient_data"]),
      model_version: z.string(),
      observation_count: z.number().int().nonnegative(),
      eligible_outlet_count: z.number().int().nonnegative(),
      message: z.string(),
      anomalies: z.array(z.object({
        outlet_id: z.string(), event_timestamp: z.string(),
        anomaly_type: z.enum(["high_returns","high_wastage","revenue_drop","revenue_spike","discount_spike","margin_drop","order_volume_anomaly","average_order_value_anomaly","profitability_anomaly","multi_factor_anomaly"]),
        severity: z.enum(["watch","elevated","high_attention"]),
        anomaly_score: z.number(), raw_model_score: z.number(),
        feature_snapshot: z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.null()])),
        summary: z.string(), recommendation: z.string(),
      })),
    }),
    timeoutMs: 120000,
  },
  runDemandForecast: {
    request: z.object({
      observations: z.array(z.object({outlet_id:z.string(),timestamp:z.string(),orders:z.number(),units_sold:z.number(),revenue:z.number(),average_order_value:z.number()})),
      horizon_hours: z.number().int().min(24).max(168),
    }),
    response: z.object({
      status:z.enum(["completed","insufficient_data"]), model_version:z.string(), training_records:z.number().int().nonnegative(), eligible_outlet_count:z.number().int().nonnegative(), message:z.string(),
      metrics:z.object({mae:z.number(),rmse:z.number(),mape:z.number().nullable()}).nullable(),
      forecasts:z.array(z.object({outlet_id:z.string(),forecast_timestamp:z.string(),predicted_orders:z.number().nonnegative()})),
    }),
    timeoutMs:120000,
  },
  getSupabaseAuthConfig: {
    request: z.object({}),
    response: z.object({
      configured: z.boolean(),
      supabase_url: z.string(),
      anon_key: z.string(),
      redirect_url: z.string(),
    }),
  },
  signInWithSupabase: {
    request: z.object({email:z.string().email(),password:z.string().min(1)}),
    response: z.object({ok:z.boolean(),access_token:z.string(),refresh_token:z.string(),expires_in:z.number().int().positive(),error:z.string()}),
    timeoutMs:15000,
  },
  refreshSupabaseSession: {
    request: z.object({refresh_token:z.string().min(1)}),
    response: z.object({ok:z.boolean(),access_token:z.string(),refresh_token:z.string(),expires_in:z.number().int().positive(),error:z.string()}),
    timeoutMs:15000,
  },
  recoverSupabasePassword: {
    request: z.object({email:z.string().email(),redirect_url:z.string()}),
    response: z.object({ok:z.boolean(),error:z.string()}),
    timeoutMs:15000,
  },
  updateSupabasePassword: {
    request: z.object({access_token:z.string().min(1),password:z.string().min(8)}),
    response: z.object({ok:z.boolean(),error:z.string()}),
    timeoutMs:15000,
  },
  signOutSupabase: {
    request: z.object({access_token:z.string().min(1)}),
    response: z.object({ok:z.boolean()}),
    timeoutMs:15000,
  },
  verifySupabaseUser: {
    request: z.object({access_token:z.string().min(1)}),
    response: z.object({
      valid:z.boolean(),
      user_id:z.string(),
      email:z.string(),
      full_name:z.string(),
      role:z.enum(["owner","manager","cashier"]).nullable(),
      is_active:z.boolean(),
      outlet_ids:z.array(z.string()),
    }),
    timeoutMs:15000,
  },
  provisionSupabaseEmployee: {
    request: z.object({owner_access_token:z.string().min(1),email:z.string().email(),full_name:z.string().min(2),role:z.enum(["owner","manager","cashier"]),outlet_ids:z.array(z.string()),send_invite:z.boolean(),auth_user_id:z.string().optional().default("")}),
    response: z.object({ok:z.boolean(),configured:z.boolean(),user_id:z.string(),invited:z.boolean(),error:z.string()}),
    timeoutMs:20000,
  },
  uploadSupabaseProductImage: {
    request: z.object({access_token:z.string().min(1),storage_path:z.string().min(1).max(240),mime_type:z.enum(["image/jpeg","image/png","image/webp"]),data_base64:z.string().min(1).max(7_100_000)}),
    response: z.object({ok:z.boolean(),storage_ready:z.boolean(),signed_url:z.string(),error:z.string()}),
    timeoutMs:30000,
  },
  signSupabaseProductImages: {
    request: z.object({access_token:z.string().min(1),storage_paths:z.array(z.string().min(1).max(240)).max(100)}),
    response: z.object({storage_ready:z.boolean(),urls:z.record(z.string(),z.string())}),
    timeoutMs:30000,
  },
  supabaseCheckout: {
    request:z.object({access_token:z.string().min(1),bill:z.record(z.string(),z.unknown()),items:z.array(z.record(z.string(),z.unknown())),movements:z.array(z.record(z.string(),z.unknown()))}),
    response:z.object({ok:z.boolean(),bill_number:z.string(),error:z.string()}),
    timeoutMs:30000,
  },
  migrateManagedData: {
    request:z.object({access_token:z.string().min(1)}),
    response:z.object({
      status:z.enum(["completed","partial","failed"]),
      started_at:z.string(),
      completed_at:z.string(),
      source:z.string(),
      rows_read:z.number().int().nonnegative(),
      inserted:z.number().int().nonnegative(),
      skipped_existing:z.number().int().nonnegative(),
      conflicts_kept_newer:z.number().int().nonnegative(),
      updated_from_managed:z.number().int().nonnegative(),
      excluded:z.number().int().nonnegative(),
      tables:z.array(z.object({
        table:z.string(),
        rows_read:z.number().int().nonnegative(),
        inserted:z.number().int().nonnegative(),
        skipped_existing:z.number().int().nonnegative(),
        conflicts_kept_newer:z.number().int().nonnegative(),
        updated_from_managed:z.number().int().nonnegative(),
        excluded:z.number().int().nonnegative(),
        error:z.string().nullable(),
      })),
      error:z.string(),
    }),
    timeoutMs:300000,
  },
  supabaseData: {
    request: z.object({
      access_token:z.string().min(1),
      operations:z.array(z.object({
        kind:z.enum(["select","insert","update","delete"]), table:z.string(),
        tables:z.array(z.object({name:z.string(),columns:z.array(z.object({property:z.string(),name:z.string(),kind:z.enum(["number","boolean","date","string"])}))})),
        sql:z.string().optional(), params:z.array(z.union([z.string(),z.number(),z.boolean(),z.null()])).optional(),
        rows:z.array(z.record(z.string(),z.unknown())).optional(), values:z.record(z.string(),z.unknown()).optional(),
        expressions:z.record(z.string(),z.object({sql:z.string(),params:z.array(z.union([z.string(),z.number(),z.boolean(),z.null()]))})).optional(),
        conflict:z.array(z.string()).optional(), ignoreConflict:z.boolean().optional(),
      })).min(1).max(100),
    }),
    response:z.object({results:z.array(z.array(z.record(z.string(),z.unknown())))}),
    timeoutMs:120000,
  },
});
